/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.TheAddress.RealEstate.gui;

/**
 *
 * @author Mitu
 */
public class rent extends javax.swing.JFrame {

    /**
     * Creates new form rent
     */
    public rent() {
        initComponents();
        rid.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        rid = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(102, 153, 255));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setText(" To Rent");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(393, 11, 80, 28);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 0, 0));
        jTextField2.setText("Rent Id");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(39, 57, 90, 23);

        rid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ridActionPerformed(evt);
            }
        });
        jPanel1.add(rid);
        rid.setBounds(290, 50, 125, 20);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(204, 51, 0));
        jTextField4.setText("Land Type");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(39, 99, 90, 23);

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox1.setText("Plot");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(290, 100, 47, 25);

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox2.setText("Built");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(420, 100, 51, 25);

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox3.setText("Semi-Built");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(540, 100, 83, 25);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(204, 51, 0));
        jTextField5.setText("Building Type");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(39, 142, 90, 23);

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox4.setText("Building");
        jPanel1.add(jCheckBox4);
        jCheckBox4.setBounds(290, 140, 71, 25);

        jCheckBox5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox5.setText("Banglow");
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(440, 140, 75, 25);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(204, 51, 0));
        jTextField6.setText("Area Type");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(39, 176, 90, 23);

        jCheckBox6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox6.setText("Residential");
        jPanel1.add(jCheckBox6);
        jCheckBox6.setBounds(289, 176, 85, 25);

        jCheckBox7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox7.setText("Commercial");
        jPanel1.add(jCheckBox7);
        jCheckBox7.setBounds(434, 176, 93, 25);

        jCheckBox8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(204, 51, 0));
        jCheckBox8.setText("Industrial");
        jPanel1.add(jCheckBox8);
        jCheckBox8.setBounds(598, 176, 79, 25);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(204, 51, 0));
        jTextField7.setText("Area (sq-ft)");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(39, 219, 90, 23);
        jPanel1.add(jTextField8);
        jTextField8.setBounds(289, 219, 255, 20);

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(204, 51, 0));
        jTextField9.setText("Location");
        jPanel1.add(jTextField9);
        jTextField9.setBounds(39, 260, 90, 23);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(289, 260, 255, 20);

        jTextField11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(204, 51, 0));
        jTextField11.setText("Land Mark");
        jPanel1.add(jTextField11);
        jTextField11.setBounds(39, 301, 90, 23);
        jPanel1.add(jTextField12);
        jTextField12.setBounds(289, 301, 255, 20);

        jTextField13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(204, 51, 0));
        jTextField13.setText("Upper Price");
        jPanel1.add(jTextField13);
        jTextField13.setBounds(39, 342, 90, 23);
        jPanel1.add(jTextField14);
        jTextField14.setBounds(289, 342, 255, 20);

        jTextField15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(204, 51, 0));
        jTextField15.setText("Lower Price");
        jPanel1.add(jTextField15);
        jTextField15.setBounds(39, 383, 90, 23);
        jPanel1.add(jTextField16);
        jTextField16.setBounds(289, 383, 255, 20);

        jTextField17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(204, 51, 0));
        jTextField17.setText("Owner's Name");
        jPanel1.add(jTextField17);
        jTextField17.setBounds(39, 432, 112, 23);
        jPanel1.add(jTextField18);
        jTextField18.setBounds(289, 434, 255, 20);

        jTextField19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(204, 51, 0));
        jTextField19.setText("Purchaser's Address");
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField19);
        jTextField19.setBounds(39, 473, 131, 23);
        jPanel1.add(jTextField20);
        jTextField20.setBounds(289, 475, 255, 20);

        jTextField21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(204, 51, 0));
        jTextField21.setText("Contact NUmber");
        jPanel1.add(jTextField21);
        jTextField21.setBounds(39, 514, 131, 23);
        jPanel1.add(jTextField22);
        jTextField22.setBounds(289, 516, 255, 20);

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 730, 67, 25);

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 730, 63, 25);

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Save");
        jPanel1.add(jButton3);
        jButton3.setBounds(160, 730, 61, 25);

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Edit");
        jPanel1.add(jButton4);
        jButton4.setBounds(440, 730, 57, 25);

        jButton5.setBackground(new java.awt.Color(102, 204, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Exit");
        jPanel1.add(jButton5);
        jButton5.setBounds(780, 730, 57, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/TheAddress/RealEstate/gui/rentw.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 0, 1030, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ridActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     ClientDashBoard1 ld = new ClientDashBoard1();
       ld.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField rid;
    // End of variables declaration//GEN-END:variables
}
